# Generated by Django 4.2.17 on 2024-12-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_complited',
            field=models.BooleanField(blank=True, default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
