# Generated by Django 4.2.17 on 2024-12-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_is_complited_alter_task_is_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
